INSERT INTO CONTACTS VALUES(DEFAULT, DEFAULT, DEFAULT, 'Kai', 'Lu', 19, 1);

INSERT INTO CONTACTS VALUES(DEFAULT, DEFAULT, DEFAULT, 'Another', 'One', 19, 2);

INSERT INTO CONTACTS VALUES(DEFAULT, DEFAULT, DEFAULT, 'Invalid', 'Name', 19, 3);